using System.Text;
using SQLErrorAtlas.Models;

namespace SQLErrorAtlas.Services;

/// <summary>Renders resolved guidance to a hand-off document (Markdown or standalone HTML).</summary>
public static class EntryExporter
{
    public static string ToMarkdown(MessageGuidance g)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {(g.MessageId is { } id ? id + " — " : "")}{g.Title}");
        sb.AppendLine();
        sb.AppendLine($"- **Urgency:** {g.Urgency}");
        if (g.IsGroupFallback)
            sb.AppendLine("- **Source:** group-level guidance (no message-specific playbook entry)");
        else if (g.Status is { } s)
            sb.AppendLine($"- **Playbook status:** {s}");
        if (g.GroupName is { } gn)
            sb.AppendLine($"- **Group:** {gn}");
        sb.AppendLine();

        Section(sb, "What it means", g.Meaning);
        Section(sb, "Investigate", g.Investigate);
        Section(sb, "Fix", g.Fix);
        if (g.HasKeyTools) Section(sb, "Key tools", g.KeyTools!);
        if (g.HasDocsUrl)
        {
            sb.AppendLine("## Reference");
            sb.AppendLine();
            sb.AppendLine(g.DocsUrl);
            sb.AppendLine();
        }
        if (g.HasRelatedIssues)
        {
            sb.AppendLine("## Related deep-dive runbooks");
            sb.AppendLine();
            foreach (var i in g.RelatedIssues) sb.AppendLine($"- Issue {i.IssueId}: {i.Title}");
            sb.AppendLine();
        }
        sb.AppendLine("---");
        sb.AppendLine($"*Generated by SQL Error Atlas · {DateTime.Now:yyyy-MM-dd HH:mm}*");
        return sb.ToString();

        static void Section(StringBuilder b, string title, string body)
        {
            if (string.IsNullOrWhiteSpace(body)) return;
            b.AppendLine($"## {title}");
            b.AppendLine();
            b.AppendLine(body.Trim());
            b.AppendLine();
        }
    }

    public static string AnalysisToMarkdown(string sourceLabel, IEnumerable<MessageGuidance> guidances)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# SQL Error Atlas — ERRORLOG analysis");
        sb.AppendLine();
        sb.AppendLine($"*{sourceLabel} · generated {DateTime.Now:yyyy-MM-dd HH:mm}*");
        sb.AppendLine();
        foreach (var g in guidances)
        {
            sb.AppendLine(ToMarkdown(g));
            sb.AppendLine();
        }
        return sb.ToString();
    }

    public static string ToHtml(string title, string markdown)
    {
        var body = MiniMarkdown.ToHtml(markdown);
        return $$"""
            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{{System.Net.WebUtility.HtmlEncode(title)}}</title>
            <style>
              :root { color-scheme: light dark; }
              body { font: 15px/1.6 -apple-system, "Segoe UI", Roboto, sans-serif; max-width: 46rem;
                     margin: 2rem auto; padding: 0 1rem; }
              h1 { font-size: 1.5rem; } h2 { font-size: 1.15rem; margin-top: 1.6rem; }
              code { background: rgba(127,127,127,.18); padding: .1em .35em; border-radius: 3px; }
              pre { background: rgba(127,127,127,.14); padding: .8rem 1rem; border-radius: 6px; overflow-x: auto; }
              pre code { background: none; padding: 0; }
              hr { border: none; border-top: 1px solid rgba(127,127,127,.35); margin: 2rem 0 1rem; }
              a { color: #2563eb; } @media (prefers-color-scheme: dark) { a { color: #7ab7ff; } }
            </style>
            </head>
            <body>
            {{body}}
            </body>
            </html>
            """;
    }
}
